name: Update YML feed

on:
  schedule:
    - cron: "0 * * * *"       # щогодини
  workflow_dispatch:          # кнопка "Run workflow"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 1) Качаємо твій фід і зберігаємо як XML
      - name: Download feed as XML (UTF-8)
        run: |
          curl -L "https://script.google.com/macros/s/AKfycbzR8U0gYUAzU8Z5xgqaME8cAB7hvvVL2JvImhr_pB0BRZO7lroBb9xOfCXOD-bPLPjn/exec" -o products_feed.xml

      # 2) Створюємо .yml з UTF-8 BOM (щоб і браузер, і сервіси читали як UTF-8)
      - name: Make YML with UTF-8 BOM
        run: |
          printf '\xEF\xBB\xBF' > products_feed.yml
          cat products_feed.xml >> products_feed.yml

      # 3) Комітимо обидва файли
      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update feed [skip ci]"
          file_pattern: |
            products_feed.xml
            products_feed.yml
