name: Update YML feed

on:
  schedule:
    - cron: "0 * * * *"   # запуск щогодини
  workflow_dispatch:      # можливість запускати вручну

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

 - name: Download YML from Google Apps Script
  run: |
    curl -L "https://script.google.com/macros/s/AKfycbwm-9xxZHaeUNxW2jv23yS8OxM-NU__HnfhTLd9_j67s-UedBPe4uXcJAy7qtV9YZhU/exec" -o products_feed.yml

      - name: Commit & push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update feed [skip ci]"
          file_pattern: products_feed.yml
